

export default function Terms() {
    return (
        <main className="relative z-10 w-full max-w-4xl mx-auto px-6 py-32 font-sans text-stone-800">
            <h1 className="font-serif text-5xl md:text-6xl text-[var(--color-dark-text)] mb-8 tracking-tight">Terms of Service</h1>
            <div className="space-y-6 text-lg text-stone-600 leading-relaxed font-medium">
                <p>Last updated: October 2024</p>
                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">1. Acceptance of Terms</h2>
                <p>By accessing or using Quantract, you are agreeing to these Terms of Service. If you do not agree, please do not use the application.</p>

                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">2. Use of Service & Data Processing</h2>
                <p>Quantract is designed to assist professionals with procurement contract review. Quantract leverages Large Language Models (LLMs) to extract key terms and verify compliance against your provided playbooks. By using our service, you acknowledge and agree to our processing methodology.</p>

                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">3. Zero Data Retention (ZDR) & Model Training</h2>
                <p>Security and confidentiality are foundational to Quantract. We maintain a strict Zero Data Retention (ZDR) policy with our LLM providers. </p>
                <ul className="list-disc pl-6 space-y-2 mt-4 text-stone-700">
                    <li><strong>No Model Training:</strong> No data provided by you (including uploaded contracts, generated insights, or chat queries) is ever used to train or fine-tune LLM foundation models.</li>
                    <li><strong>In-Memory Processing:</strong> Customer data included in requests and responses with these LLMs is not persisted by the provider and exists solely in memory in order to process a request.</li>
                    <li><strong>Auto-Deletion:</strong> Quantract enforces a strict ephemeral lifecycle. No data is stored or restored after 15 days. Each document is automatically deleted, including any insights or KPIs generated by the user.</li>
                </ul>

                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">4. Client Responsibilities</h2>
                <p>Quantract does not provide formal legal advice. All output from our platform should be reviewed and verified by qualified professionals within your organization. You are responsible for safeguarding your authentication credentials and for any activity that occurs under your account.</p>

                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">5. Limitations of Liability</h2>
                <p>Quantract shall not be liable for any indirect, incidental, special, consequential or punitive damages, including loss of profits, data, or goodwill, arising from your use of the service or reliance on extracted contract data.</p>

                <h2 className="font-serif text-3xl text-[var(--color-dark-text)] mt-12 mb-4">6. Contact</h2>
                <p>For any questions regarding these Terms or our Data Handling practices, please contact legal@quantract.ai.</p>
            </div>
        </main>
    );
}
